name: Docker Image Delivery

on:
  release:
    types: [created]

jobs:
  deliver-to-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Push to Docker w/jib
      run: ./gradlew jib -D jib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -D jib.to.auth.password=${{ secrets.DOCKER_PWD }} jib
